### ISSUE TITLE
Sample data appears to not be available from pip installation

### ISSUE THREAD

**Issue by daxm** [erdogant/benfordslaw#1]
How can I use the "bl.import_example()" feature?  The sample/test code provided doesn't work if you pip install benfordslaw (I haven't tried cloning this repo to see if it works then).

**Comment by daxm** [comment]
I should mention/add that I copied the USA_2016_election_primary_results.zip into a "data" folder under my project directory in an attempt to "make" the import_example() work.

Here is my code:
```python
>>> import benfordslaw as bl
>>> df = bl.import_example()
[BL.import_example] Loading USA_2016_election_primary_results.zip..
[BL.import_example] Oops! Example data not found!
>>> quit()
```

**Comment by erdogant** [comment]
Dear Daxm,

Thank you for mentioning this issue!
I fixed the issue, try to update the library with:

`pip install -U benfordslaw`

The version should be >= 0.1.3

**Comment by daxm** [comment]
Confirmed fixed.  Thanks!
