### ISSUE TITLE
Incorrect determination nth digit distribution

### ISSUE THREAD

**Issue by Sebas-Greveling** [erdogant/benfordslaw#10]
The nth digit distribution is calculated wrong.

The empirical_counts is offset due to the assumption that digit_range is from 1-9. However, for digits larger than 1, 0 is a valid value. Hence, digit_range = 0-9 for digits > 1. Additionally, the nth digits are determined correctly and stored in digits[Iloc]. However, digits[Iloc] is not used for the empirical_counts, rather digits is.

To make _count_digit work for every digit, line 303 should be:
empirical_counts[i - digit_range[0]] = list(digits[Iloc]).count(i)

**Comment by erdogant** [comment]
Thank you for finding this and mentioning this issue! I fixed it asap.
You can now update with:

`pip install -U benfordslaw
`
