### ISSUE TITLE
AttributeError: 'FigureCanvasTkAgg' object has no attribute `'set_window_title'`

### ISSUE THREAD

**Issue by ruben-mar** [erdogant/benfordslaw#11]
I get 

`File "/home/user/anaconda3/envs/environment/lib/python3.10/site-packages/benfordslaw/benfordslaw.py", line 186, in plot fig.canvas.set_window_title('Percentage First Digits')
AttributeError: 'FigureCanvasTkAgg' object has no attribute `'set_window_title'``

with this code

`bl = benfordslaw(alpha=0.05)

results = bl.fit(amounts)

bl.plot(title='Amounts of transactions - 1st digit', barcolor=[0.5, 0.5, 0.5], fontsize=12, barwidth=0.4)`

Using benfordslaw v 1.2.0 and Python 3.10.4

**Comment by erdogant** [comment]
Thanks for reporting! Not sure where this comes from. But I fixed the issue!
Please update to the latest version with:

`pip install -U benfordslaw`

**Comment by ruben-mar** [comment]
The AttributeError is no more with the version 1.2.1! Thank you for the fix.
