### ISSUE TITLE
Pos < 0 results in incorrect probabilities

### ISSUE THREAD

**Issue by danielmccarville** [erdogant/benfordslaw#13]
benfordslaw() returns incorrect expected probabilities when pos < 0. This shows up clearly in the Example info: https://erdogant.github.io/benfordslaw/pages/html/Examples.html#last-digit-test.

The Example where pos=-1 shows that the the last digit is expected to be '1' about 30% of the time. That's not true.  It appears to be using the formula for the first significant digit, instead of using convolution to find the probability of the n-th digit.

Recommended solution would be to restrict pos > 0.

**Comment by danielmccarville** [comment]
Dug into the repo more to figure out what's happening. The __init__ method in benfordslaw (line 52) uses the absolute value of pos. That's not intuitive, since the distribution of the first digit and the last digit aren't related at all. Similarly, the distribution of the second digit and second-to-last digit aren't the same. 

I'd recommend removing that absolute value from all of them.

**Comment by erdogant** [comment]
It took some time but I fixed this issue. I now assume a uniform distribution for every position > 3 and position < 0.
I also updated the documentation pages, including the figures.
