### ISSUE TITLE
comment says "Get only non-zero values " but code says > 1

### ISSUE THREAD

**Issue by czengnn** [erdogant/benfordslaw#5]
https://github.com/erdogant/benfordslaw/blob/ea5de2a7085e7800104bf7df86e0ddf48fd591c9/benfordslaw/benfordslaw.py#L238-L239

    # Get only non-zero values
    data = data[data>1]

should we take 
data = data[data>0]

or should the comment say take only values that are not 0 or 1 ?

**Comment by erdogant** [comment]
Thank your for mentioning this issue. I fixed it and released a new version.

Install with:

`pip install -U benfordslaw`
