### ISSUE TITLE
About digital numbers smaller than 1

### ISSUE THREAD

**Issue by jnzhuang** [erdogant/benfordslaw#6]
Hi Erdogan,

My array goes like this: [-0.89, 1.18, 0.28, 0.0032, ...]. Most numbers in my array is between -1 and 1.

If I directly use your Benford method, I get many NaN. To obtain correct results, I have to multiply my array by a large number, e.g., 1000 or 1e6. How can I use your code to let the method recognize that the first digit of 0.0032 is 3 instead of 0? Or do I have to manually multiply a large number myself?

Thank you!

**Comment by erdogant** [comment]
Correct. It does take the first number. A bit of pre-processing seems like a good suggestion!
