### ISSUE TITLE
ChiSquare error being thrown: can an explanation be provided instead?

### ISSUE THREAD

**Issue by javadba** [erdogant/benfordslaw#7]
I am trying to use this library more or less as either a binary indicator of "benford or not" or a  probability indicator of same.  So *any* distribution should be possible to send into it. If the distribution is weird - then say "sorry, nope."  

Instead consider:

```
bl = benfordslaw(alpha=0.05)
x = np.linspace(0,1000,1001)
x = np.append(x,[1,1,1,1,1,1,])
isben2 = bl.fit(x)
print(f"isben2 {isben2}")
```

Instead of a "nope" we get:

> ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
0.0009950248756218905

Note that even just using `x` without the extra `np.append()` results in the same error.  So .. what does this mean? Should I add my own code to catch that exception and then say "nope" ?  The problem with that is we don't get any probability and also it is unclear whether that exception were due to some other unexplained data problem.

fyi the entire stacktrace is

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8d38f0d591c2>", line 4, in <module>
    isben2 = bl.fit(x)
  File "/usr/local/lib/python3.9/site-packages/benfordslaw/benfordslaw.py", line 109, in fit
    tstats, Praw = chisquare(counts_emp, f_exp=counts_exp)
  File "/usr/local/lib/python3.9/site-packages/scipy/stats/stats.py", line 6852, in chisquare
    return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
  File "/usr/local/lib/python3.9/site-packages/scipy/stats/stats.py", line 6694, in power_divergence
    raise ValueError(msg)
ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
0.0009950248756218905
```

**Comment by erdogant** [comment]
I can not reproduce the error.
Can you tell me the version you are using?

```
import benfordslaw
print(benfordslaw.__version__)

```
Should be >= 1.0.2

I get the following results when using your code:
```
import numpy as np
from benfordslaw import benfordslaw
bl = benfordslaw(alpha=0.05)
x = np.linspace(0,1000,1001)
x = np.append(x,[1,1,1,1,1,1,])
isben2 = bl.fit(x)
print(f"isben2 {isben2}")

[benfordslaw] >Analyzing digit position: [1]
[benfordslaw] >[chi2] Anomaly detected! P=5.47798e-80, Tstat=393.145
isben2 {'P': 5.4779835775992096e-80, 't': 393.14541596537117, 'percentage_emp': array([[ 1.        , 11.72962227],
       [ 2.        , 11.03379722],
       [ 3.        , 11.03379722],
       [ 4.        , 11.03379722],
       [ 5.        , 11.03379722],
       [ 6.        , 11.03379722],
       [ 7.        , 11.03379722],
       [ 8.        , 11.03379722],
       [ 9.        , 11.03379722]])}

```

**Comment by javadba** [comment]
```
import benfordslaw
   ...: print(benfordslaw.__version__)
1.0.2
```

**Comment by erdogant** [comment]
update with:

`pip install -U benfordslaw`

**Comment by erdogant** [comment]
Well this one is tricky. More information about it can be found [here](https://github.com/scipy/scipy/issues/13362). It is a feature, not a bug. 

You can either change your input slightly (remove one of the 1s)

```
x = np.linspace(0,1000,1001)
x = np.append(x,[1,1,1,1,1])
```

Or you can use another method:

`bl = benfordslaw(alpha=0.05, method='ks')
`
I created a new update that will inform better about what to do in such case.

`pip install -U benfordslaw
`
